import { copyFileSync, existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { Adapter, AgentConfig, RunOpts, RunResult } from './base.js';
import { execWithTimeout } from './base.js';

/** Parse token usage from codex CLI output */
function parseTokens(output: string): { tokens_in?: number; tokens_out?: number } {
  const m = output.match(/[Tt]okens[^:]*:\s*([\d,]+)\s*(?:in(?:put)?)\s*[/,]\s*([\d,]+)\s*(?:out(?:put)?)/);
  if (m) return { tokens_in: parseInt(m[1].replace(/,/g, ''), 10), tokens_out: parseInt(m[2].replace(/,/g, ''), 10) };
  const inM = output.match(/input_tokens\s*[:=]\s*([\d,]+)/);
  const outM = output.match(/output_tokens\s*[:=]\s*([\d,]+)/);
  if (inM || outM) return {
    tokens_in: inM ? parseInt(inM[1].replace(/,/g, ''), 10) : undefined,
    tokens_out: outM ? parseInt(outM[1].replace(/,/g, ''), 10) : undefined,
  };
  return {};
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function userCodexHome(): string {
  return process.env.CODEX_HOME || join(homedir(), '.codex');
}

function syncCodexAuthFiles(codexHome: string): void {
  const sourceHome = userCodexHome();
  if (sourceHome === codexHome) return;

  for (const fileName of ['auth.json', 'credentials.json', 'installation_id']) {
    const sourcePath = join(sourceHome, fileName);
    const targetPath = join(codexHome, fileName);
    try {
      if (!existsSync(sourcePath)) continue;
      if (!statSync(sourcePath).isFile()) continue;
      // Codex login refreshes rotate auth data. Long-running FlowCrew retries
      // must not keep using a stale per-stage copy after the global login state
      // has moved forward.
      copyFileSync(sourcePath, targetPath);
    } catch {
      // Missing auth files are fine for environments that authenticate another way.
    }
  }
}

export function writeCodexConfig(codexHome: string, role: AgentConfig): string {
  mkdirSync(codexHome, { recursive: true });
  syncCodexAuthFiles(codexHome);
  const lines = [
    '# Generated by FlowCrew. Do not edit global Codex config for this run.',
  ];
  if (role.model && role.model !== 'default') lines.push(`model = ${tomlString(role.model)}`);
  if (role.reasoning_effort && role.reasoning_effort !== 'default') {
    lines.push(`reasoning_effort = ${tomlString(role.reasoning_effort)}`);
  }
  lines.push(`developer_instructions = ${tomlString(role.prompt ?? '')}`);
  const configPath = join(codexHome, 'config.toml');
  writeFileSync(configPath, `${lines.join('\n')}\n`);
  return configPath;
}

export function stageCodexHome(runDir: string, stageId: string): string {
  return join(runDir, 'stages', stageId, 'codex_home');
}

export function codexArgs(): string[] {
  return ['--dangerously-bypass-approvals-and-sandbox'];
}

/**
 * OpenAI Codex CLI adapter.
 *
 * Non-interactive: `codex exec "prompt"` (no sandbox/approval prompts)
 * Resume: `codex exec resume --last "follow-up"`
 * Interactive: `codex` (TUI mode, needs PTY)
 *
 * Flags:
 *   --dangerously-bypass-approvals-and-sandbox: no approval prompts/sandbox
 *   --model: override model
 *   --config reasoning_effort="<effort>": set reasoning effort
 */
export class CodexAdapter implements Adapter {
  async run(prompt: string, role: AgentConfig, opts: RunOpts): Promise<RunResult> {
    const codexHome = stageCodexHome(opts.runDir, opts.stageId);
    writeCodexConfig(codexHome, role);
    const args = ['exec', ...codexArgs()];
    // Use `--` to terminate option parsing before the prompt. Without this,
    // codex CLI treats prompts beginning with `-` (e.g. briefs whose first
    // line is `---` YAML frontmatter) as unrecognized flags and aborts with
    // `error: unexpected argument`. The `--` separator is the standard
    // POSIX convention codex itself recommends in its tip output.
    args.push('--');
    args.push(prompt);

    const result = await execWithTimeout('codex', args, {
      cwd: opts.workDir,
      timeout_ms: opts.timeout_ms,
      liveLogPath: join(opts.runDir, 'stages', opts.stageId, 'live.log'),
      env: { CODEX_HOME: codexHome },
      abortSignal: opts.abortSignal,
    });
    const tokens = parseTokens(result.output);
    if (tokens.tokens_in !== undefined) result.tokens_in = tokens.tokens_in;
    if (tokens.tokens_out !== undefined) result.tokens_out = tokens.tokens_out;
    return result;
  }

}

export function createAdapter(): Adapter {
  return new CodexAdapter();
}
